"plan":"AARP MedicareComplete SecureHorizons (HMO)",
"company":"UnitedHealthcare",
"type":"Local HMO",
"premium":"$79.00 ",
"drugdeductable":null,
"drugbenefittype":"Enhanced",
"moop":"$5,900 ",
"rating":"3.5",
"gapcoverage":"No Gap Coverage",
"drugbenefitdetail":"EA",
"snp":null,
"snp_details":null,
"companies":null,
"year":"2013"},
